### ISSUE TITLE
RandomGuid and RandomDouble?

### ISSUE THREAD

**Issue by fleed** [microsoft/coyote#48]
There are two methods to "control" randomness: RandomBoolean and RandomInteger.
How to control Guid and Double values?

**Comment by akashlal** [comment]
A `double` is easy. Create a `System.Random` object `r` with seed set to `Coyote.RandomInteger`. This is enough, because setting the seed uniquely determines the sequence of doubles that you get from `r`. It seems that there is no way to set the seed for `Guid.NewGuid`. So instead you can write a loop that generates an array of `16` random bytes and then initializes the `GUID` [using the array](https://docs.microsoft.com/en-us/dotnet/api/system.guid.-ctor?view=netcore-3.1#System_Guid__ctor_System_Byte___). A random byte is simply `RandomInteger(64)`.

**Comment by fleed** [comment]
Thank you @akashlal
