### ISSUE TITLE
Persisting actors

### ISSUE THREAD

**Issue by fleed** [microsoft/coyote#49]
Is there a suggested way to persist actors?
I have long running state machines and the application might restart multiple times before they complete.
Are there guidelines for this scenario?

**Comment by akashlal** [comment]
We do not have anything documented at the moment. One pattern that I can recommend is the following. Define a base actor class with all the persistence logic, so that derived actor classes don't have to repeat the work. The base class defines the initialization method for the actor. It reads in the state and hydrates the actor from where it last left off. It also has a method for taking the snapshot of the current state of the actor. This method can be abstract and implemented by the derived class, according to what is important to remember for that actor.

**Comment by fleed** [comment]
Thank you! Please consider it for future samples

**Comment by codeputer** [comment]
Can you tell me, or point me to some documents, which explain the difference between Actors of Coyote, and Actors of DAPR?

Is there a difference and why?

Thanks
Richard

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by pdeligia** [comment]
Hi @codeputer, you can read about this here: https://microsoft.github.io/coyote/learn/programming-models/actors/why-actors

**Comment by codeputer** [comment]
I think I see where the confusion it – coyote is a testing framework for Actor frameworks, but its not *really* an actor framework, but something that can exercise and find flaws with an Actor framework.

Why then call it an Actor Framework when it doesn’t have the implementation of an Actor framework?  Call it a testing framework for Actors IMO.

R

**Comment by akashlal** [comment]
Depends on what you mean by an "Actor Framework" :)  I do see now that people mean many things when they say actor, than I originally thought. Our notion of actors is a very classical take on a simple programming construct for concurrency: there are threads, tasks, and there are actors.

**Comment by codeputer** [comment]
I define an actor as a turn base concurrency framework, which makes each actor (behaviour and data) single treaded.

I’m thinking that is not Coyote (sorry will spend more time on docs), as I’ve simply classified in my head as a testing framework specifically for Actors.

R

**Comment by akashlal** [comment]
That part you will get. With Coyote, you can do things like:
```
using Microsoft.Coyote.Actors;
class Client : Actor { ... }
```
And then start creating actors, which execute in a single-threaded turn-based fashion. Even if you don't use `coyote test` you can still program your application using these actors. [More here.](https://microsoft.github.io/coyote/learn/programming-models/actors/overview)

**Comment by pdeligia** [comment]
To add to the discussion:

Btw, I don't believe we explicitly call Coyote an actor framework, and if we do it might be some stale text that we need to update. Coyote started as a fork of our [P#](https://github.com/p-org/PSharp) project, that is only about in-memory actors (well actually state-machines that are basically actors with state transitions), but the focus and scope changed significantly in Coyote.

Coyote is "a set of libraries and tools for building reliable asynchronous software". In its essence (and what is the core value here), Coyote is a systematic testing engine for exercising concurrency and nondeterminism, and reproducing bugs.

Besides systematically testing actors*, we can also tests async tasks (based on the [async/await style of programming](https://docs.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/task-based-asynchronous-pattern-tap) in C#).

Saying this, there is a main difference between the above two programming models that we support: for tasks, although we have a drop-in-replacement type (`Microsoft.Coyote.Tasks.Task`) which contains the hooks Coyote needs to take control during testing, when not running it systematic testing mode it is just a pass-through to `System.Threading.Tasks`, i.e. we don't have a production implementation for tasks. For actors though, we have a very efficient and lightweight production runtime (that has only dependency on TPL), because C#/.NET itself does not support the notion of an actor. We also expose a StateMachine type (as mentioned above). We could decouple our Actor/StateMachines from Coyote and just build them on top as a separate library. They just use tasks under the hood so that is possible, but because by having intimate knowledge of them we can do much better exploration during testing.

Also, although we are able to systematically test actors, we can only support testing our own type, and not any actor implementation (in-memory or distributed) available out there. Although there are techniques as described by @akashlal [here](https://github.com/microsoft/coyote/issues/34) to achieve this.

**Comment by pdeligia** [comment]
@codeputer hope this helps and clarifies things.

(btw, I just made some edits on my answer above for better clarity)
