### ISSUE TITLE
Reschdule after AutoResetEvent.Set

### ISSUE THREAD

**Issue by aoli-al** [microsoft/coyote#495]
Hi developers, 

I'm wondering why coyote won't reschedule after `AutoResetEvent.Set` is called. [Currently](https://github.com/microsoft/coyote/blob/51b3db9823e42a1b5ce87189e670017de8e24215/Source/Test/Rewriting/Types/Threading/WaitHandle.cs#L434), it only enables a task that waits for the signal and continue. 

Given a program:

```C#
public static async Task Test()
{
    var autoResetEvent = new AutoResetEvent(false);
    var task = Task.Run(() =>
    {
        Console.WriteLine("Enter thread!");
        autoResetEvent.WaitOne();
        Console.WriteLine("Wait done!");
    });

    Console.WriteLine("Thread started!");
    Thread.Sleep(1000 * 2);
    autoResetEvent.Set();
    Console.WriteLine("Event set!");
    await Task.WhenAll(task);
}
```

Coyote can never schedule `Console.WriteLine("Event set!");` after `Console.WriteLine("Wait done!");` because the reschedule will only be triggered at `await Task.WhenAll(task);`.

**Comment by akashlal** [comment]
This is likely an "optimization" that Coyote does, and avoids doing a scheduling point at `Set`. Coyote, in general, only cares about ordering of synchonization operations, not "local" actions like writing to console. One option is to create a wrapper for Console.WriteLine that calls SchedulingPoint.Insert before printing to console, and then you will see the intended behavior. Otherwise, Coyote is waiting to hit a sync operation before rescheduling.

**Comment by akashlal** [comment]
It is `SchedulingPoint.Interleave` (not insert)

**Comment by akashlal** [comment]
The issue in this example, like the previous example, is not with `Set` considered as a local operation. In this example, the issue is likely with `Reset`. In general, scheduling points should be inserted _before_ a non-local operation. In this example, the `Reset` should have trigged a scheduling decision (just before the reset actually happens). 

Documenting all places where scheduling points are inserted is a great idea.

**Comment by aoli-al** [comment]
Sounds good! Yes, I do agree that all scheduling point should be inserted before a non-local operation. Shall I create another issue about `Reset` or just leave this issue open?

**Comment by akashlal** [comment]
A separate issue for Reset, with your second example, would be good. Even better if you can contribute a PR for it.
